# Generated by Django 6.0.3 on 2026-05-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0003_remove_service_staff_booking_time_staffservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
