# Generated by Django 6.0.3 on 2026-05-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0004_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_bookings', to='salonapp.user'),
        ),
    ]
